# Site settings
title: Mirko Kiefer - My Point of View.
name: Mirko Kiefer
email: email@mirkokiefer.com
description: "I write about all things web and mobile."
baseurl: ""
url: "http://mirkokiefer.com"
username: "mirkokiefer"

# Build settings
markdown: redcarpet
permalink: /blog/:year/:month/:title
excerpt_separator: "{more}"
paginate: 5